//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detallesVentas
    {
        public int Id { get; set; }
        public int cantidad { get; set; }
        public decimal precioCompra { get; set; }
        public decimal precioVenta { get; set; }
        public int id_llanta { get; set; }
        public int id_venta { get; set; }
    
        public virtual llantas llantas { get; set; }
        public virtual ventas ventas { get; set; }
    }
}
