//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detallesVentas
    {
        public int Id { get; set; }
        public int cantidad { get; set; }
        public decimal precioCompra { get; set; }
        public decimal precioVenta { get; set; }
        public int id_llanta { get; set; }
        public int id_venta { get; set; }
    
        public virtual llantas llantas { get; set; }
        public virtual ventas ventas { get; set; }
    }
}
