//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class llantas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public llantas()
        {
            this.detallesCompras = new HashSet<detallesCompras>();
            this.detallesVentas = new HashSet<detallesVentas>();
        }
    
        public int Id { get; set; }
        public string modelo { get; set; }
        public string descripcion { get; set; }
        public int rin { get; set; }
        public int ancho { get; set; }
        public int perfil { get; set; }
        public int carga { get; set; }
        public string imagen { get; set; }
        public int stock { get; set; }
        public int existencia { get; set; }
        public decimal precioVenta { get; set; }
        public decimal precioCompra { get; set; }
        public System.DateTime ultActualizacion { get; set; }
        public int id_proveedor { get; set; }
        public int id_subcategoria { get; set; }
        public int id_marca { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detallesCompras> detallesCompras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detallesVentas> detallesVentas { get; set; }
        public virtual marcas marcas { get; set; }
        public virtual proveedores proveedores { get; set; }
        public virtual subcategorias subcategorias { get; set; }
    }
}
