//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class llantas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public llantas()
        {
            this.detallesCompras = new HashSet<detallesCompras>();
            this.detallesVentas = new HashSet<detallesVentas>();
        }
    
        public int Id { get; set; }
        [Required(ErrorMessage = "Ingrese el modelo")]
        public string modelo { get; set; }
        [Required(ErrorMessage = "Ingrese la descripción")]
        public string descripcion { get; set; }
        [Required(ErrorMessage = "Ingrese el rin")]
        public int rin { get; set; }
        [Required(ErrorMessage = "Ingrese el ancho")]
        public int ancho { get; set; }
        [Required(ErrorMessage = "Ingrese el perfil")]
        public int perfil { get; set; }
        [Required(ErrorMessage = "Ingrese la carga")]
        public int carga { get; set; }
        public string imagen { get; set; }
        public int stock { get; set; }
        public int existencia { get; set; }
        [Required(ErrorMessage = "Ingrese el precio de venta")]
        public decimal precioVenta { get; set; }
        [Required(ErrorMessage = "Ingrese el precio de compra")]
        public decimal precioCompra { get; set; }
        public System.DateTime ultActualizacion { get; set; }
        public int id_proveedor { get; set; }
        public int id_subcategoria { get; set; }
        public int id_marca { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detallesCompras> detallesCompras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detallesVentas> detallesVentas { get; set; }
        public virtual marcas marcas { get; set; }
        public virtual proveedores proveedores { get; set; }
        public virtual subcategorias subcategorias { get; set; }
    }
}
