//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class contextLlantera : DbContext
    {
        public contextLlantera()
            : base("name=contextLlantera")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();            
        }

        public virtual DbSet<categorias> categorias { get; set; }
        public virtual DbSet<compras> compras { get; set; }
        public virtual DbSet<detallesCompras> detallesCompras { get; set; }
        public virtual DbSet<detallesVentas> detallesVentas { get; set; }
        public virtual DbSet<envios> envios { get; set; }
        public virtual DbSet<llantas> llantas { get; set; }
        public virtual DbSet<marcas> marcas { get; set; }
        public virtual DbSet<paqueterias> paqueterias { get; set; }
        public virtual DbSet<proveedores> proveedores { get; set; }
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<subcategorias> subcategorias { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
        public virtual DbSet<ventas> ventas { get; set; }
    }
}
