//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class contextLlantera : DbContext
    {
        public contextLlantera()
            : base("name=contextLlantera")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();            
        }

        public virtual DbSet<categorias> categorias { get; set; }
        public virtual DbSet<compras> compras { get; set; }
        public virtual DbSet<detallesCompras> detallesCompras { get; set; }
        public virtual DbSet<detallesVentas> detallesVentas { get; set; }
        public virtual DbSet<envios> envios { get; set; }
        public virtual DbSet<llantas> llantas { get; set; }
        public virtual DbSet<marcas> marcas { get; set; }
        public virtual DbSet<paqueterias> paqueterias { get; set; }
        public virtual DbSet<proveedores> proveedores { get; set; }
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<subcategorias> subcategorias { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
        public virtual DbSet<ventas> ventas { get; set; }
    }
}
