//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public usuarios()
        {
            this.ventas = new HashSet<ventas>();
        }
    
        public int Id { get; set; }
        public string nombre { get; set; }
        public string apellidoPaterno { get; set; }
        public string apellidoMaterno { get; set; }
        public string telefono { get; set; }
        public string correoElectronico { get; set; }
        public string contrasenia { get; set; }
        public string estado { get; set; }
        public string municipio { get; set; }
        public string colonia { get; set; }
        public string calle { get; set; }
        public Nullable<int> numeroCasa { get; set; }
        public Nullable<int> cp { get; set; }
        [Range(100000000000,9999999999999999, ErrorMessage = "Debe ser entre 12 y 16 dígitos")]
        public string tarjetaCredito { get; set; }
        public string tipoTarjeta { get; set; }
        [Range(2000,2050, ErrorMessage = "Ingrese un año válido")]
        public Nullable<int> anio { get; set; }
        [Range(1, 12, ErrorMessage = "Ingrese un mes válido")]
        public Nullable<int> mes { get; set; }
        [Range(100,999, ErrorMessage = "Ingrese un CVV válido")]
        public Nullable<int> cvv { get; set; }
        public int id_rol { get; set; }
    
        public virtual roles roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ventas> ventas { get; set; }
    }
}
